const calvinQuotes = [
    "So long, Pop! I'm off to check my tiger trap.",
    "Undoubtedly.",
    "Mom, can I take up the floorboards in my room and make a secret passageway?",
    "How quietly do you think we can nail these back in?",
    "I rigged a tuna fish sandwich yesterday, so I'm sure to have a tiger by now!",
    "Tigers will do anything for a tuna fish sandwich!",
    "So Dad, what do I do when I catch a tiger?",
    "It was Hobbes, Dad! He was jumping on the bed! Honest!", 
    "Whew! That was a close one!",
    "Hey! Aren't you going to say good night to Hobbes?!",
    "Go to sleep, you sissy.",
    "Outrage! Why should I go to bed? I'm not tired! It's only 7:30! This is tyranny! I'm- zzzzz.",
    "Get ready! I hear one coming!",
    "AAIEEE!! A monster in the Hallway!!",
    "Any monsters under my bed tonight?!",
    "I'd hate to have to torch one with my flame thrower!",
    "Mom can I drive on the way back?",
    "I promise I won't crash.",
    "Can I work the gas while you steer?",
    "Tragically, this serene metropolis lies directly beneath the Hoover Dam...",
    "That smells like barf!",
    "Ha! I pulled the plug! Down the drain with you! Die, fiend! die, die!!",
    "Believe it, lady.",
    "Bad news Dad, your polls are way down.",
    "Hey Susie Derkins, is that your face, or is a possum stuck in your collar?",
    "A squid eyeball sandwich.",
    "Houston, we have a negative on that orbit trajectory.", 
    "Mom, can I set fire to my bed mattress?",
    "Can I ride my tricycle on the roof?",
    "Hello Dad! It is now three in the morning. Do you know where I am?",
    "Tommy Chesnutt did once, and now nobody does.",
    "And here comes an inflammable chemical truck! Oh No!!",
    "Making speed bumps. ",
    "None dare attack us! We rule all!!",
    "Yaah! Death to oatmeal!",
    "You'll never escape, vile glop! Die! Die!",
    "I'm not eating this green stuff. Yecchh!",
    "Having transformed myself into a werewolf, I search for human sacrifice!",
    "I cannot  answer this question, as it is against my religious principles.",
    "We are a fierce and dirty band of cutthroat pirates!",
    "A bag of dead bugs I collected from our window sills.",
    "Fortunately, our motto is &quot;Be prepared.&quot;",
    "Well, Hobbes, we did it again. We're separated from the troop and hopelessly lost.",
    "AAAAUGH! Tiger attack!",
    "You sissy. Mom always takes your side!",
    "I'm going to be the next Houdini! Tie me to this chair and I'll escape!",
    "Ha! The great Calvin can escape from anything!",
    "Ahh! That's tighter! Pull the other way! The other way.",
    "&quot;Live for revenge,&quot; is gonna be my motto if you don't get me out of this.",
    "Oh, no, not tortellini! I hate tortellini!! Oh, gross! Yecch Tortellini!!",
    "Oh, no. That can only mean our real teacher rocketed back to Saturn to report to her superious!",
    "Always the victor, he lets out a triumphant roar!",
    "Calvin the criminal is about to face justice! Angry throngs turn out to watch his execution!",
    "Open your mouth and close your eyes, and you will get a big surprise.",
    "Uh oh. Hang on, he got away.",
    "Santa Claus: Kindly old elf, or CIA spook?",
    "This is a purely hypothetical case, Mr.Smartypants.", 





]


const hobbesQuotes = [
   
    "We're kind of stupid that way.",
    "No, really, I can't eat another bite!",
    "Well, you were the one playing the cymbals!!",
    "You have a flame thrower??",
    "Yeah. Let me see your bat a minute.",
    "Nothing to do ?! You could read a book! Or write a letter! Or take a walk!",
    "That's because she wanted another tiger, not you!",
    "Who do we smooch then?",
    "Just so long as we don't get hungry.",
    "We're lost again.",
    "Sunny and Warmer today, high in the upper thirties.",
    "Most children have seen a million murders on television.",
    "Well, I've always been partial to redheads.",
    "I think we play saxophone for an all-girl cabaret in New Orleans.",
    "Should I tell her you're tied up at the moment, ha ha?",
    "Good thing you're doing this before you tried it under water.",
    "&quot;Sit tight,&quot; ha ha! I'll get your scout manual. ",
    "Hey, look, here's a motto! I didn't know you had a motto! Wow, what fun!",
    "I'll quiz you. What do you do for a second-degree burn?",
    "Hmph, if I was in your predicament, I'd treat me with a lot more respect. Do you say you're sorry?",
    "You got yourself into this &quot;Mr. Houdini,&quot; not me.",
    "Here's how you say &quot;Banana&quot; in morse. Dash dot dot dot, dot dash...",
    "Your're worried about the salamander incident aren't you?",
    "Should I tell her you're tied up at the moment, ha ha?",
    "How cynically enterprising of you.",
    "I'm a reflection of Calvin's imagination.",
    "Sometimes I think the surest sign that intelligent life exists elsewhere is that none of it has tried to contact us.",
    "I'm a tiger. It's a simple life.",
    "I'm glad you're not a tiger. I'd hate to have to compete with you for food.",
    "Why should I worry about posterity? What's posterity ever done for me?",
    "The world is full of magic things, patiently waiting for our senses to grow sharper.",
    "Why do they call them buildings? They ought to call them 'collapsings'.",
    "We're so busy watching out for what's just ahead of us that we don't take time to enjoy where we are.",
    "Sometimes when I'm talking, my words can't keep up with my thoughts. I wonder why we think faster than we speak.",
    "It's funny how day by day, nothing changes, but when you look back, everything is different.",
    "The days are just packed.",
    "Life is like topography, Hobbes. There are summits of happiness and success, flat stretches of boring routine, and valleys of frustration and failure.",
    "The surest sign that intelligent life exists elsewhere in the universe is that it has never tried to contact us.",
    "The world isn't fair, Calvin.",
    "I know, but why isn't it ever unfair in my favor?",
    "I'm a great believer in luck. The harder I work, the more I have of it.",
    "Happiness isn't good enough for me! I demand euphoria!",
    "I'm not crazy. I prefer the term 'mentally hilarious'.",
    "I'm not a pessimist. I'm an optimist with experience.",
    "I don't know which is worse: that everyone has his price, or that the price is always so low.",
    "You know, Hobbes, some days even my lucky rocket ship underpants don't help.",
    "It's not denial. I'm just very selective about the reality I accept.",
    "If good things lasted forever, would we appreciate how precious they are?",
    "I don't want to tame anything. I just want to go exploring.",
    "I'm against having emotions, not against using them.",
    "The problem with people is they forget that most of the time it's the small things that count.",
    "I like to see the world through my own eyes.",
    "We're so busy watching out for what's just ahead of us that we don't take time to enjoy where we are.",
    "I think night time is dark so you can imagine your fears with less distraction.",
    "Life's disappointments are harder to take when you don't know any swear words.",
    "I'm just trying to decide whether life is passing me by or trying to run me over.",
    "I'm not a big fat panda. I'm THE big fat panda.",
    "The world is full of monsters with friendly faces.",
    "The more you do, the more you can do.",
    "Don't just fly, soar.",
    "Yesterday is history, tomorrow is a mystery, but today is a gift. That's why it's called the present.",
    "The secret ingredient is always love.",
    "Sometimes life is a thousand shades of gray.",
    "You are too concerned with what was and what will be. There's a saying: Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the 'present.'",
    "One often meets his destiny on the road he takes to avoid it.",
    "The past can hurt. But the way I see it, you can either run from it or learn from it.",
    "You have to put the past behind you before you can move on.",
    "Look inside yourself, Simba. You are more than what you have become. You must take your place in the Circle of Life.",
    "You can't change your past, but you can change your future.",
    "The problem is not the problem. The problem is your attitude about the problem.",
    "Oh yes, the past can hurt. But you can either run from it or learn from it.",
    "Sometimes the right path is not the easiest one.",
    "It's not what you look at that matters, it's what you see.",
    "You control your destiny. You don't need magic to do it. And there are no magical shortcuts to solving your problems.",
    "You must learn to let go of the past, so you can embrace the future.",
  



]



const spiffQuotes = [
   
    "The valiant spaceman spiff has been captured!",
    "The aliens doubtlessly want the secret formula to the atomic napalm neutralizer!",
    "Moments from the torture chamber, Spiff springs into action.",
    "I’ll set my fertilizer on deep fat fry.",
    "We join spaceman spiff on the distant planet Zorg.",
    "Chew electric death, snarling cur! ",
    "Suddenly, a searing bolt of deadly frap ray slices across the blackness! Our Hero is unfazed.",
    "Spiff is going down! Can he make it?? Is this the end?!?",
    "Spaceman Spiff cooly draws his death ray blaster...",
    "Spaceman Spiff triumphs over impossible odds!",
  "Spaceman Spiff navigates the treacherous asteroid belt!",
  "Spaceman Spiff outwits the alien overlords!",
  "Spaceman Spiff explores the mysterious dark side of the moon!",
  "Spaceman Spiff discovers a hidden alien civilization!",
  "Spaceman Spiff boldly goes where no one has gone before!",
  "Spaceman Spiff encounters a hostile alien queen!",
  "Spaceman Spiff uncovers the secrets of a forbidden planet!",
  "Spaceman Spiff dodges laser blasts with lightning-fast reflexes!",
  "Spaceman Spiff vanquishes the menacing space pirates!",
  "Spaceman Spiff, interplanetary explorer extraordinary, is marooned on a distant planet!",
  "Spaceman Spiff blasts off into the unknown!",
  "Spaceman Spiff hurtles through the cosmos in his interplanetary cruiser!",
  "Spaceman Spiff lands on a hostile alien planet!",
  "Spaceman Spiff fights off a horde of alien invaders!",
  "Spaceman Spiff escapes from the clutches of the evil Zog!",
  "Spaceman Spiff battles the dreaded forces of darkness!",
  "Spaceman Spiff bravely faces the unknown!",
  "Spaceman Spiff embarks on a daring mission to save the galaxy!",
  "Spaceman Spiff encounters strange and bizarre extraterrestrial lifeforms!",
  "In a galaxy far, far away, Spaceman Spiff defies gravity!",
  "As the stars shimmer in the vast expanse of space, Spaceman Spiff takes flight!",
  "With a burst of cosmic energy, Spaceman Spiff rockets into the unknown!",
  "Amidst the swirling nebulae, Spaceman Spiff embarks on a daring adventure!",
  "In the darkest corners of the universe, Spaceman Spiff fights for justice!",
  "On the frontiers of the cosmos, Spaceman Spiff wages a battle against alien foes!",
  "From the depths of the Milky Way, Spaceman Spiff emerges as a hero!",
  "In a realm beyond time and space, Spaceman Spiff fearlessly explores!",
  "As the constellations align, Spaceman Spiff discovers a new frontier!",
  "In a universe of infinite possibilities, Spaceman Spiff's journey begins!",
    

]


const susieQuotes = [
    "You do not! Don’t be disgusting.",
    "Miss Wormwood!!",
    "What on earth makes you think I’d want to sit in a stupid tree in the first place?!?",
    "Insurance?? What a dumb idea!",
    "Hey Calvin, you want to play house?",
    "Okay… First, you come home from work. Then I come home from work.", 
    "I love winter days. They’re so peaceful",
    "I brought a letter I wrote to our congressman!",
    "It’s a secret note, so don’t read it.",
    "Girls have moved delicate heinies.",
    "Darn you, Calvin!! You’re gonna answer to my parents if I can’t get my master’s degree!",  
    "I think one of us has been eating too much paste in art class.",
    "Calvin, you're impossible!",
    "You never cease to amaze me with your uncanny ability to turn the simplest task into a complete fiasco.",
    "I can't believe I have to sit next to you every day in school.",
    "You may think you're clever, Calvin, but you're just obnoxious.",
    "Sometimes I wonder how you manage to get dressed in the morning.",
    "I don't know how you come up with these wild ideas, Calvin, but they're always ridiculous.",
    "You're the most infuriating boy I've ever met!",
    "I wish you'd stop trying to involve me in your crazy schemes.",
    "I'd rather spend my time with someone who has a shred of common sense.",
    "You're hopeless, Calvin. Absolutely hopeless.",
    "You have no sense of responsibility, Calvin.",
    "Do you ever think before you act, Calvin?",
    "I can't believe I have to explain basic concepts to you, Calvin.",
    "You make everything so much more difficult than it needs to be.",
    "You're a perpetual nuisance, Calvin.",
    "I've had enough of your nonsense, Calvin!",
    "You're the reason why we can't have nice things, Calvin.",
    "I can't wait for summer vacation to get away from you, Calvin.",
    "You need to grow up and start taking things seriously, Calvin.",
    "Why do I even bother talking to you, Calvin?",
    "You're like a hurricane of chaos and trouble, Calvin.",
    "You're exhausting to be around, Calvin.",
    "I don't know how your brain works, Calvin, but it's definitely not like everyone else's.",
    "You have an answer for everything, don't you, Calvin?",
    "I can't believe I fell for one of your pranks again, Calvin.",
    "You need to learn some manners, Calvin.",
    "I'm not falling for your tricks, Calvin. I know better now.",
    "I wish you'd show some respect for others, Calvin.",
    "You always manage to ruin everything, Calvin.",
    "I'm not impressed by your antics, Calvin.",
    "You need a serious reality check, Calvin.",
    "You have a talent for making every situation worse, Calvin.",
    "I don't know how you manage to be so consistently irritating, Calvin.",
    "You're the epitome of chaos, Calvin.",
    "I can't believe I have to put up with your antics day after day, Calvin.",
    "You have an uncanny ability to turn any conversation into an argument, Calvin.",
    "I don't know why I even bother trying to reason with you, Calvin.",
    "You're like a never-ending source of frustration, Calvin.",
    "I can't fathom how you function with such a warped sense of reality, Calvin.",
    "You thrive on mischief and it's exhausting, Calvin.",
    "I wish I could go a single day without being dragged into your absurd adventures, Calvin.",
    "You're a constant distraction, Calvin.",
    "I don't understand how you can be so blissfully unaware of your own foolishness, Calvin.",
    "You're like a magnet for trouble, Calvin.",
    "I can't decide if you're incredibly naive or deliberately obtuse, Calvin.",
    "You have an incredible talent for pushing people's buttons, Calvin.",
    "I don't know why I let you get under my skin, Calvin.",
    "You're a master of testing my patience, Calvin.",
    "I can't believe I fell for your trickery once again, Calvin.",
    "You always manage to find a way to make things more complicated than they need to be, Calvin.",
    "You have a unique talent for taking a simple task and turning it into a disaster, Calvin.",
    "I wish I could understand the inner workings of your mind, Calvin, but it's a mystery to me.",
    "You're like a perpetual whirlwind of chaos, Calvin.",
    "I don't know how you come up with your outrageous ideas, Calvin, but they never cease to amaze me.",
    "You have an answer for everything, even when it doesn't make any sense, Calvin.",
    "I can't believe you managed to drag me into another one of your schemes, Calvin.",
    "You need a serious reality check, Calvin.",
    "You're a walking contradiction, Calvin.",
    "I don't know why I bother trying to reason with you, Calvin.",
    "You have a remarkable ability to turn the simplest task into a catastrophe, Calvin.",
    "You're like a tornado of chaos, Calvin.",
    "I can't believe I let you get under my skin, Calvin.",
    "You have an incredible knack for ruining perfectly good moments, Calvin.",
    "I don't know how you manage to make everything about you, Calvin.",
    "You're a constant source of exasperation, Calvin.",
    "I wish you'd think before you act, Calvin.",
    "You're like a perpetual thorn in my side, Calvin.",
    "I can't understand why you enjoy causing so much trouble, Calvin.",
    "You always find a way to make things more complicated than they need to be, Calvin.",
    "You have an uncanny ability to turn any situation into a disaster, Calvin.",
    "I don't know why I keep falling for your manipulations, Calvin.",
    "You're like a master of mischief, Calvin.",
    "I can't believe I let you drag me into your world of chaos, Calvin.",

    

]


const momQuotes = [
    "No, Calvin.",
    "Of course not, Calvin.",
    "What a noisy kid!",
    "CALVIN! Quiet down and quit that splashing! I don’t want to have to clean the whole bathroom!",
    "Your stuffed tiger is in the washing machine.",
    "Calvin! What are you doing to our yard?!?",
    "It’s your fault we didn’t have a sweet little girl! Your stupid chromosome!! Not mine!!",
    "Very grim, Calvin you’re still having oatmeal.",
    "Calvin! You’re going to be late for school! Get up!",
    "Now are you through charging around the house. Or are you going to fall down the stairs again?",
    "Your dinner's getting cold Calvin.",
    "I’ll bet he grows up to be an architect.",
    "We...Are...Buying… A Video Player.",
    "Calvin, did you brush your teeth?",
    "Eat your vegetables, Calvin. They're good for you.",
    "Calvin, how many times have I told you to pick up your toys?",
    "Time to go to bed, Calvin. It's past your bedtime.",
    "Calvin, stop jumping on the furniture!",
    "Don't forget to wash your hands before dinner, Calvin.",
    "Calvin, did you finish your homework?",
    "Put on your jacket, Calvin. It's cold outside.",
    "Calvin, stop teasing your sister!",
    "Did you remember to feed the dog, Calvin?",
    "Calvin, stop making that mess in the kitchen!",
    "It's time for your annual check-up, Calvin.",
    "Calvin, be careful with that vase. It's fragile.",
    "Don't forget to wear sunscreen, Calvin. You'll get sunburned.",
    "Calvin, stop running in the house!",
    "Finish your milk, Calvin. It's good for your bones.",
    "Calvin, clean up your room. It's a mess.",
    "Did you finish your chores, Calvin?",
    "Calvin, did you do your laundry?",
    "Be home before dark, Calvin.",
    "Calvin, don't forget to say please and thank you.",
    "Stop arguing with your father, Calvin.",
    "Calvin, you need to do your homework before you can play.",
    "Remember to be respectful to your elders, Calvin.",
    "Calvin, you're not going out without a jacket.",
    "Turn off the TV, Calvin. You've been watching for too long.",
    "Calvin, don't talk with your mouth full.",
    "Did you make your bed, Calvin?",
    "Calvin, put away your phone and focus on your studies.",
    "Finish your dinner, Calvin. There are starving children in the world.",
    "Calvin, don't forget to walk the dog.",
    "Stop playing video games and go outside, Calvin.",
    "Calvin, stop procrastinating and do your homework.",
    "Did you finish your book report, Calvin?",
    "Calvin, you're spending too much time on the computer.",
    "Don't forget to pack your lunch, Calvin.",
    "Calvin, you need to take a shower. You're starting to smell.",
    "Put away your toys, Calvin. We have guests coming over.",
    "Calvin, don't forget to wear a helmet when you ride your bike.",
    "Did you remember to turn off the lights, Calvin?",
    "Calvin, you need to clean up after yourself.",
]


const dadQuotes = [
    "Bring it home and stuff it, Calvin! Can’t you see I’m busy?",
    "Calvin, stop that disgusting drooling!",
    "Sheesh",
    "What’s all this noise? You’re supposed to be asleep!",
    "Good idea, Calvin. It’s a plate of toxic waste that will turn you into a mutat if you eat it.",
    "Hobbes was not jumping on the bed! Now go to sleep ",
    "Taste it you’ll love it.",
    "I just live here.",
    "That does it, young man! You are excused to your room!",
    "Don’t look at me! I’m done shopping!",
    "Then it will build character.",
    "What is that kid doing?! It sounds like a chair thumping around the room.",
    "You tied yourself up?? What on earth are you doing?!",
    "Have you seen how absorbed Calvin is with those tinkertoys? He’s creating whole worlds over there!",
    "Oh, knock it off. Some of us have to wear a tie everyday.",
    "This season gets less jolly every year.",
    "Calvin, don't forget to do your homework.",
    "Turn off the lights when you leave the room, Calvin.",
    "Calvin, did you clean your room like I asked?",
    "I'm not made of money, Calvin.",
    "Calvin, eat your vegetables. They're good for you.",
    "Money doesn't grow on trees, Calvin.",
    "Calvin, did you finish mowing the lawn?",
    "Don't forget to take out the trash, Calvin.",
    "Calvin, respect your elders.",
    "I don't have time for your shenanigans, Calvin.",
    "Calvin, did you walk the dog?",
    "Money doesn't buy happiness, Calvin.",
    "Calvin, turn down the volume. It's too loud.",
    "Don't forget to change the oil in the car, Calvin.",
    "Calvin, life isn't fair. Get used to it.",
    "We're not lost, Calvin. I know exactly where we are.",
    "Calvin, did you put away your toys?",
    "Don't stay up too late, Calvin. You need your sleep.",
    "Calvin, stop slouching. Sit up straight.",
    "Because I said so, Calvin.",
    "Calvin, did you finish your book report?",
    "Money doesn't grow on trees, Calvin. It's time to get a job.",
    "Calvin, respect your mother.",
    "Did you lock the front door, Calvin?",
    "Calvin, stop playing video games and go outside.",
    "I don't know how you managed to break that, Calvin.",
    "Calvin, don't forget to floss.",
    "Did you take a jacket with you, Calvin? It might get cold.",
    "Calvin, don't interrupt when adults are talking.",
    "Money doesn't buy happiness, Calvin. But it helps.",
    "Calvin, stop jumping on the bed!",
    "Did you finish your science project, Calvin?",
    "Calvin, don't forget to feed the fish.",
    "When I was your age, Calvin...",
    "Calvin, don't touch that, it's hot.",
    "Did you finish your chores, Calvin?",
    "Calvin, stop asking so many questions.",
    "Because I'm your father, Calvin, that's why.",
    "Calvin, did you clean up after the dog?",
    "Don't forget to wear sunscreen, Calvin.",
    "Calvin, did you finish your math homework?",
    "Money doesn't grow on trees, Calvin. It's time to start saving.",
    "Calvin, did you turn off the sprinklers?",
    "Don't leave the refrigerator door open, Calvin.",
    "Calvin, don't forget to walk the neighbor's dog.",
    "I don't understand why you kids need so many gadgets, Calvin.",
    "Calvin, put on your seatbelt. Safety first.",
    "Did you take the garbage cans to the curb, Calvin?",
    "Calvin, don't forget to call your grandparents.",
    "We're not lost, Calvin. I'm just taking a scenic route.",

]
